CC=cc
CCFLAGS=-Wall -Wextra -Werror -g
#MANDATORY
NAME_SERVER=server
NAME_CLIENT=client
NAME=$(NAME_SERVER) $(NAME_CLIENT) 
SRC_PATH=src/
SRCS_NAMES_SERVER=server.c
SRCS_NAMES_CLIENT=client.c
OBJ_PATH=build/
OBJS_NAMES_SERVER=$(SRCS_NAMES_SERVER:.c=.o)
OBJS_SERVER=$(addprefix $(OBJ_PATH), $(OBJS_NAMES_SERVER))
OBJS_NAMES_CLIENT=$(SRCS_NAMES_CLIENT:.c=.o)
OBJS_CLIENT=$(addprefix $(OBJ_PATH), $(OBJS_NAMES_CLIENT))
#BONUS
NAME_SERVER_BONUS=$(addsuffix _bonus, $(NAME_SERVER))
NAME_CLIENT_BONUS=$(addsuffix _bonus, $(NAME_CLIENT))
NAME_BONUS=$(NAME_SERVER_BONUS) $(NAME_CLIENT_BONUS)
SRC_PATH_BONUS=src_bonus/
SRCS_NAMES_SERVER_BONUS= server_bonus.c
SRCS_NAMES_CLIENT_BONUS= client_bonus.c
SRCS_SERVER_BONUS=$(addprefix $(SRC_PATH_BONUS), $(SRCS_NAMES_SERVER_BONUS))
OBJ_PATH_BONUS=build_bonus/
OBJS_NAMES_SERVER_BONUS=$(SRCS_NAMES_SERVER_BONUS:.c=.o)
OBJS_SERVER_BONUS=$(addprefix $(OBJ_PATH_BONUS), $(OBJS_NAMES_SERVER_BONUS))
OBJS_NAMES_CLIENT_BONUS=$(SRCS_NAMES_CLIENT_BONUS:.c=.o)
OBJS_CLIENT_BONUS=$(addprefix $(OBJ_PATH_BONUS), $(OBJS_NAMES_CLIENT_BONUS))
#GENERAL
LIB_STATIC_NAME = libft.a
LIB_PATH=lib/
LIBS_FLAGS=-l$(patsubst lib%.a, %, $(LIB_STATIC_NAME)) -L$(LIB_PATH)
LIB_STATIC= $(addprefix $(LIB_PATH) , $(INCLUDE_PATH))
INCLUDE_PATH=./include/ ./lib/*/include/
INCLUDE_FLAG=$(addprefix -I , $(INCLUDE_PATH))
RM=rm -f

all: libs $(NAME)

$(NAME_SERVER): $(OBJS_SERVER) $(LIB_STATIC)
	$(CC) $(CCFLAGS) $(OBJS_SERVER) $(INCLUDE_FLAG) $(LIBS_FLAGS) -o $(NAME_SERVER)

$(NAME_CLIENT): $(OBJS_CLIENT) $(LIB_STATIC)
	$(CC) $(CCFLAGS) $(OBJS_CLIENT) $(INCLUDE_FLAG) $(LIBS_FLAGS) -o $(NAME_CLIENT)

libs:
	make all -C lib/libft

bonus: libs $(NAME_BONUS)

$(NAME_SERVER_BONUS): $(OBJS_SERVER_BONUS) $(LIB_STATIC)
	$(CC) $(CCFLAGS) $(OBJS_SERVER_BONUS) $(INCLUDE_FLAG) $(LIBS_FLAGS) -o $(NAME_SERVER_BONUS)

$(NAME_CLIENT_BONUS): $(OBJS_CLIENT_BONUS) $(LIB_STATIC)
	$(CC) $(CCFLAGS) $(OBJS_CLIENT_BONUS) $(INCLUDE_FLAG) $(LIBS_FLAGS) -o $(NAME_CLIENT_BONUS)

$(OBJ_PATH)%.o: $(SRC_PATH)%.c
	mkdir -p $(OBJ_PATH)
	$(CC) $(CCFLAGS) -c $< -o $@ $(INCLUDE_FLAG)

$(OBJ_PATH_BONUS)%.o: $(SRC_PATH_BONUS)%.c
	mkdir -p $(OBJ_PATH_BONUS)
	$(CC) $(CCFLAGS) -c $< -o $@ $(INCLUDE_FLAG)

clean:
	make clean -C lib/libft
	$(RM) $(OBJS_SERVER) $(OBJS_CLIENT) $(OBJS_SERVER_BONUS) $(OBJS_CLIENT_BONUS)

fclean: clean
	make fclean -C lib/libft
	$(RM) $(NAME) $(NAME_BONUS)

re: fclean all bonus

norm:
	norminette -R CheckDefine $(INCLUDE_PATH)*.h
	norminette -R CheckForbiddenSourceHeader $(SRC_PATH)*.c

.PHONY=all bonus clean fclean re norm libs
